# Site settings
#
# All variables in this file are accessible in the templates via {{ site.myvariable }}.
#
title: "Bt"
tagline: "&nbsp;&nbsp;java bittorrent done right"
description: >
 <a href="https://github.com/atomashpolskiy/bittorrent" target="_blank">Bt</a> is a modern Java 8 BitTorrent library.
 It offers good performance, reliability and is highly customizable.
baseurl: "/bittorrent"
url: "https://atomashpolskiy.github.io"
repository: atomashpolskiy/bittorrent
github:
  url: "https://atomashpolskiy.github.io/bittorrent"
  repo: "https://github.com/atomashpolskiy/bittorrent"
author:
  name: Andrei Tomashpolskiy
  email: nordmann89@gmail.com
timezone: Europe/Moscow
encoding: utf-8

# Other settings
#
permalink: pretty
paginate: 5

# Build settings
#
markdown: kramdown
#theme:
gems:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Github defaults
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
